name: Build, Tag, and Release EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name fast_folder_delete_gui fast_folder_delete_gui.py

      - name: Install GitHub CLI
        run: choco install gh -y

      - name: Create Tag and Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=autobuild-${GITHUB_SHA}
          gh release create "$TAG" dist/fast_folder_delete_gui.exe --title "Automated Build $TAG" --notes "Automated build for commit $GITHUB_SHA" --latest --repo $GITHUB_REPOSITORY --target $GITHUB_SHA 