name: Build and Release EXE

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name fast_folder_delete_gui fast_folder_delete_gui.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: fast_folder_delete_gui-exe
          path: dist/fast_folder_delete_gui.exe

  release:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'release'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: fast_folder_delete_gui-exe
          path: .

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: fast_folder_delete_gui.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 