name: Build and Release EXE

on:
  push:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name fast_folder_delete_gui fast_folder_delete_gui.py

      # This will upload the EXE as an artifact for every build (push to main or release)
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: fast_folder_delete_gui-exe
          path: dist/fast_folder_delete_gui.exe

# The EXE will be available for download from the Actions run artifacts for every build.
# If you want to also attach it to GitHub Releases, let me know! 